name: Playwright API Checks
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "URL to run tests against"
        required: true
        default: https://my-site.com
  repository_dispatch:
    types: ["run-my-tests", "run-my-tests-2"]
jobs:
  run_automation_tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}${{ github.event.client_payload. }}
    steps:
      - name: Set Test Type For Happy and Preview Environment
        if: github.event_name == 'repository_dispatch' && github.event.action == 'happy-turkey-run' || env.TYPE == 'happy'
        run: |
          echo "PARAMS= --grep @happy  --grep-invert @unsatisfactory" >> $GITHUB_ENV
          echo "HEADERS_CHECKS=false" >> $GITHUB_ENV 

      - name: Run Playwright tests
        run: |
          echo "Environment: $ENVIRONMENT"
          echo "TYPE = $TYPE"
          echo "The github event is: ${{ github.event_name }}"
          echo "Run Test Here"
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Dump client_payload context
        run: echo '${{ toJSON(client_payload) }}'
